apiVersion: apps/v1
kind: Deployment
metadata:
  name: tareas-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tareas-api
  template:
    metadata:
      labels:
        app: tareas-api
    spec:
      containers:
        - name: tareas-api
          image: tareas-api:latest
          ports:
            - containerPort: 8001
          envFrom:
            - configMapRef:
                name: tareas-api-config
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: tareas-api-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tareas-api-secrets
                  key: DB_PASSWORD
          command: ["/bin/sh", "-c"]
          args:
            - |
              sleep 10 && \
              php artisan migrate --force && \
              php artisan serve --host=0.0.0.0 --port=8001
